<a href="https://colab.research.google.com/github/amitabh16kgpian/Machine-Learning-Projects/blob/main/Spam_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import nltk

In [42]:
import pandas as pd

In [43]:
import numpy as np

In [44]:
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [45]:
import re
from nltk.corpus import stopwords

In [46]:
df = pd.read_csv('/content/drive/MyDrive/SMSSpamCollection', sep='\t', names =["label","message"])

In [48]:
print(df)

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]


In [49]:
len(df)
corpus =[]

In [50]:
#Cleaning the text

In [51]:
for i in range((len(df))):
  review = re.sub('[^a-zA-Z]',' ' ,df['message'][i])
  review = review.lower()
  review = review.split()
  review = [PorterStemmer().stem(word) for word in review if word not in set(stopwords.words('english'))]
  review = ' '.join(review)
  corpus.append(review)

In [26]:
print(df)

     label                                            message
0      ham  go jurong point crazi avail bugi n great world...
1      ham                              ok lar joke wif u oni
2     spam  free entri wkli comp win fa cup final tkt st m...
3      ham                u dun say earli hor u c alreadi say
4      ham               nah think goe usf live around though
...    ...                                                ...
5567  spam  nd time tri contact u u pound prize claim easi...
5568   ham                              b go esplanad fr home
5569   ham                                  piti mood suggest
5570   ham  guy bitch act like interest buy someth els nex...
5571   ham                                     rofl true name

[5572 rows x 2 columns]


In [52]:
df['label'] = df['label'].replace(to_replace = 'spam',value=1)

In [53]:
df['label'] = df['label'].replace(to_replace = 'ham',value=0)


In [54]:
print(df)

      label                                            message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567      1  This is the 2nd time we have tried 2 contact u...
5568      0               Will ü b going to esplanade fr home?
5569      0  Pity, * was in mood for that. So...any other s...
5570      0  The guy did some bitching but I acted like i'd...
5571      0                         Rofl. Its true to its name

[5572 rows x 2 columns]


In [56]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
X = CountVectorizer(max_features = 5000).fit_transform(corpus).toarray()

In [57]:
Y = df['label']

In [58]:
print(X,Y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] 0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: label, Length: 5572, dtype: int64


In [59]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [61]:
X.shape

(5572, 5000)

In [62]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state= 0)

In [65]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train,Y_train)

In [66]:
y_pred = spam_detect_model.predict(X_test)

In [68]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test,y_pred)

In [69]:
print(accuracy)

0.9847533632286996
